name: WC_Deploy
on:
  workflow_call:
      
  # Allows you to run this workflow manually from the Actions tab
    inputs:
      PROJECT_NAME:
        description: 'Project Level'
        required: true
        type: string
      APP_NAME:
        description: 'Application Name'
        required: true
        type: string
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:         
   
  WC_Deploy_DMQ_Cluster:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: '${{ inputs.PROJECT_NAME }}'
      APP_NAME: '${{ inputs.APP_NAME }}'
      ACTIONS_STEP_DEBUG: true
   
    defaults:
      run:
        shell: bash
    steps:    
    - name: ${{ env.PROJECT_NAME }}
      run: echo "${{ env.PROJECT_NAME }}"
